# Generated by Django 5.0 on 2024-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='heading',
            field=models.CharField(max_length=200),
        ),
    ]
