# Generated by Django 5.0 on 2024-02-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_blogpost_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
